# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QComboBox,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(793, 703)
        MainWindow.setMaximumSize(QSize(793, 703))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 771, 351))
        self.preprocess = QWidget()
        self.preprocess.setObjectName(u"preprocess")
        self.preprocess.setEnabled(True)
        font = QFont()
        font.setPointSize(9)
        self.preprocess.setFont(font)
        self.preprocess.setLayoutDirection(Qt.LeftToRight)
        self.preprocess_label_filename = QLabel(self.preprocess)
        self.preprocess_label_filename.setObjectName(u"preprocess_label_filename")
        self.preprocess_label_filename.setGeometry(QRect(40, 20, 151, 21))
        self.preprocess_pushButton_save_arg = QPushButton(self.preprocess)
        self.preprocess_pushButton_save_arg.setObjectName(u"preprocess_pushButton_save_arg")
        self.preprocess_pushButton_save_arg.setGeometry(QRect(520, 290, 101, 24))
        self.preprocess_lineEdit_filename = QLineEdit(self.preprocess)
        self.preprocess_lineEdit_filename.setObjectName(u"preprocess_lineEdit_filename")
        self.preprocess_lineEdit_filename.setGeometry(QRect(210, 20, 113, 21))
        self.preprocess_pushButton_run = QPushButton(self.preprocess)
        self.preprocess_pushButton_run.setObjectName(u"preprocess_pushButton_run")
        self.preprocess_pushButton_run.setGeometry(QRect(630, 290, 101, 24))
        self.preprocess_label_outlier_detector = QLabel(self.preprocess)
        self.preprocess_label_outlier_detector.setObjectName(u"preprocess_label_outlier_detector")
        self.preprocess_label_outlier_detector.setGeometry(QRect(40, 60, 151, 21))
        self.preprocess_lineEdit_outlier_detector_param = QLineEdit(self.preprocess)
        self.preprocess_lineEdit_outlier_detector_param.setObjectName(u"preprocess_lineEdit_outlier_detector_param")
        self.preprocess_lineEdit_outlier_detector_param.setGeometry(QRect(210, 100, 113, 21))
        self.preprocess_label_outlier_detector_param = QLabel(self.preprocess)
        self.preprocess_label_outlier_detector_param.setObjectName(u"preprocess_label_outlier_detector_param")
        self.preprocess_label_outlier_detector_param.setGeometry(QRect(40, 100, 151, 21))
        self.preprocess_lineEdit_train_size = QLineEdit(self.preprocess)
        self.preprocess_lineEdit_train_size.setObjectName(u"preprocess_lineEdit_train_size")
        self.preprocess_lineEdit_train_size.setGeometry(QRect(210, 140, 113, 21))
        self.preprocess_label_train_size = QLabel(self.preprocess)
        self.preprocess_label_train_size.setObjectName(u"preprocess_label_train_size")
        self.preprocess_label_train_size.setGeometry(QRect(40, 140, 151, 21))
        self.preprocess_label_num_splits = QLabel(self.preprocess)
        self.preprocess_label_num_splits.setObjectName(u"preprocess_label_num_splits")
        self.preprocess_label_num_splits.setGeometry(QRect(40, 180, 151, 21))
        self.preprocess_lineEdit_num_splits = QLineEdit(self.preprocess)
        self.preprocess_lineEdit_num_splits.setObjectName(u"preprocess_lineEdit_num_splits")
        self.preprocess_lineEdit_num_splits.setGeometry(QRect(210, 180, 113, 21))
        self.preprocess_comboBox_outlier_detector = QComboBox(self.preprocess)
        self.preprocess_comboBox_outlier_detector.addItem("")
        self.preprocess_comboBox_outlier_detector.addItem("")
        self.preprocess_comboBox_outlier_detector.addItem("")
        self.preprocess_comboBox_outlier_detector.setObjectName(u"preprocess_comboBox_outlier_detector")
        self.preprocess_comboBox_outlier_detector.setGeometry(QRect(210, 60, 111, 22))
        self.tabWidget.addTab(self.preprocess, "")
        self.train = QWidget()
        self.train.setObjectName(u"train")
        self.train.setFont(font)
        self.train_label_quiet = QLabel(self.train)
        self.train_label_quiet.setObjectName(u"train_label_quiet")
        self.train_label_quiet.setGeometry(QRect(40, 20, 151, 21))
        self.train_label_cuda = QLabel(self.train)
        self.train_label_cuda.setObjectName(u"train_label_cuda")
        self.train_label_cuda.setGeometry(QRect(40, 60, 151, 21))
        self.train_label_dataset = QLabel(self.train)
        self.train_label_dataset.setObjectName(u"train_label_dataset")
        self.train_label_dataset.setGeometry(QRect(40, 100, 151, 21))
        self.train_label_split_id = QLabel(self.train)
        self.train_label_split_id.setObjectName(u"train_label_split_id")
        self.train_label_split_id.setGeometry(QRect(40, 140, 151, 21))
        self.train_label_train_size = QLabel(self.train)
        self.train_label_train_size.setObjectName(u"train_label_train_size")
        self.train_label_train_size.setGeometry(QRect(40, 180, 151, 21))
        self.train_label_batch_size = QLabel(self.train)
        self.train_label_batch_size.setObjectName(u"train_label_batch_size")
        self.train_label_batch_size.setGeometry(QRect(40, 220, 151, 21))
        self.train_label_model = QLabel(self.train)
        self.train_label_model.setObjectName(u"train_label_model")
        self.train_label_model.setGeometry(QRect(40, 260, 151, 21))
        self.train_label_num_hidden_layers = QLabel(self.train)
        self.train_label_num_hidden_layers.setObjectName(u"train_label_num_hidden_layers")
        self.train_label_num_hidden_layers.setGeometry(QRect(450, 20, 151, 21))
        self.train_label_hidden_size = QLabel(self.train)
        self.train_label_hidden_size.setObjectName(u"train_label_hidden_size")
        self.train_label_hidden_size.setGeometry(QRect(450, 60, 151, 21))
        self.train_label_dropout = QLabel(self.train)
        self.train_label_dropout.setObjectName(u"train_label_dropout")
        self.train_label_dropout.setGeometry(QRect(450, 100, 151, 21))
        self.train_label_learning_rate = QLabel(self.train)
        self.train_label_learning_rate.setObjectName(u"train_label_learning_rate")
        self.train_label_learning_rate.setGeometry(QRect(450, 140, 151, 21))
        self.train_label_weight_decay = QLabel(self.train)
        self.train_label_weight_decay.setObjectName(u"train_label_weight_decay")
        self.train_label_weight_decay.setGeometry(QRect(450, 180, 151, 21))
        self.train_label_num_epochs = QLabel(self.train)
        self.train_label_num_epochs.setObjectName(u"train_label_num_epochs")
        self.train_label_num_epochs.setGeometry(QRect(450, 220, 151, 21))
        self.train_lineEdit_cuda = QLineEdit(self.train)
        self.train_lineEdit_cuda.setObjectName(u"train_lineEdit_cuda")
        self.train_lineEdit_cuda.setGeometry(QRect(210, 60, 113, 21))
        self.train_lineEdit_dataset = QLineEdit(self.train)
        self.train_lineEdit_dataset.setObjectName(u"train_lineEdit_dataset")
        self.train_lineEdit_dataset.setGeometry(QRect(210, 100, 113, 21))
        self.train_lineEdit_split_id = QLineEdit(self.train)
        self.train_lineEdit_split_id.setObjectName(u"train_lineEdit_split_id")
        self.train_lineEdit_split_id.setGeometry(QRect(210, 140, 113, 21))
        self.train_lineEdit_train_size = QLineEdit(self.train)
        self.train_lineEdit_train_size.setObjectName(u"train_lineEdit_train_size")
        self.train_lineEdit_train_size.setGeometry(QRect(210, 180, 113, 21))
        self.train_lineEdit_batch_size = QLineEdit(self.train)
        self.train_lineEdit_batch_size.setObjectName(u"train_lineEdit_batch_size")
        self.train_lineEdit_batch_size.setGeometry(QRect(210, 220, 113, 21))
        self.train_lineEdit_num_hidden_layers = QLineEdit(self.train)
        self.train_lineEdit_num_hidden_layers.setObjectName(u"train_lineEdit_num_hidden_layers")
        self.train_lineEdit_num_hidden_layers.setGeometry(QRect(620, 20, 113, 21))
        self.train_lineEdit_hidden_size = QLineEdit(self.train)
        self.train_lineEdit_hidden_size.setObjectName(u"train_lineEdit_hidden_size")
        self.train_lineEdit_hidden_size.setGeometry(QRect(620, 60, 113, 21))
        self.train_lineEdit_dropout = QLineEdit(self.train)
        self.train_lineEdit_dropout.setObjectName(u"train_lineEdit_dropout")
        self.train_lineEdit_dropout.setGeometry(QRect(620, 100, 113, 21))
        self.train_lineEdit_learning_rate = QLineEdit(self.train)
        self.train_lineEdit_learning_rate.setObjectName(u"train_lineEdit_learning_rate")
        self.train_lineEdit_learning_rate.setGeometry(QRect(620, 140, 113, 21))
        self.train_lineEdit_weight_decay = QLineEdit(self.train)
        self.train_lineEdit_weight_decay.setObjectName(u"train_lineEdit_weight_decay")
        self.train_lineEdit_weight_decay.setGeometry(QRect(620, 180, 113, 21))
        self.train_lineEdit_num_epochs = QLineEdit(self.train)
        self.train_lineEdit_num_epochs.setObjectName(u"train_lineEdit_num_epochs")
        self.train_lineEdit_num_epochs.setGeometry(QRect(620, 220, 113, 21))
        self.train_checkbox_quiet = QCheckBox(self.train)
        self.train_checkbox_quiet.setObjectName(u"train_checkbox_quiet")
        self.train_checkbox_quiet.setGeometry(QRect(210, 20, 76, 20))
        self.train_comboBox_model = QComboBox(self.train)
        self.train_comboBox_model.addItem("")
        self.train_comboBox_model.addItem("")
        self.train_comboBox_model.addItem("")
        self.train_comboBox_model.setObjectName(u"train_comboBox_model")
        self.train_comboBox_model.setGeometry(QRect(210, 260, 111, 22))
        self.train_pushButton_save_arg = QPushButton(self.train)
        self.train_pushButton_save_arg.setObjectName(u"train_pushButton_save_arg")
        self.train_pushButton_save_arg.setGeometry(QRect(520, 290, 101, 24))
        self.train_pushButton_run = QPushButton(self.train)
        self.train_pushButton_run.setObjectName(u"train_pushButton_run")
        self.train_pushButton_run.setGeometry(QRect(630, 290, 101, 24))
        self.train_label_quiet_description = QLabel(self.train)
        self.train_label_quiet_description.setObjectName(u"train_label_quiet_description")
        self.train_label_quiet_description.setGeometry(QRect(240, 18, 81, 21))
        self.tabWidget.addTab(self.train, "")
        self.test = QWidget()
        self.test.setObjectName(u"test")
        self.test.setFont(font)
        self.test_label_cuda = QLabel(self.test)
        self.test_label_cuda.setObjectName(u"test_label_cuda")
        self.test_label_cuda.setGeometry(QRect(40, 20, 151, 21))
        self.test_lineEdit_cuda = QLineEdit(self.test)
        self.test_lineEdit_cuda.setObjectName(u"test_lineEdit_cuda")
        self.test_lineEdit_cuda.setGeometry(QRect(210, 20, 113, 21))
        self.test_label_dataset = QLabel(self.test)
        self.test_label_dataset.setObjectName(u"test_label_dataset")
        self.test_label_dataset.setGeometry(QRect(40, 60, 151, 21))
        self.test_lineEdit_dataset = QLineEdit(self.test)
        self.test_lineEdit_dataset.setObjectName(u"test_lineEdit_dataset")
        self.test_lineEdit_dataset.setGeometry(QRect(210, 60, 113, 21))
        self.test_label_split_id = QLabel(self.test)
        self.test_label_split_id.setObjectName(u"test_label_split_id")
        self.test_label_split_id.setGeometry(QRect(40, 100, 151, 21))
        self.test_lineEdit_split_id = QLineEdit(self.test)
        self.test_lineEdit_split_id.setObjectName(u"test_lineEdit_split_id")
        self.test_lineEdit_split_id.setGeometry(QRect(210, 100, 113, 21))
        self.test_label_model = QLabel(self.test)
        self.test_label_model.setObjectName(u"test_label_model")
        self.test_label_model.setGeometry(QRect(40, 140, 151, 21))
        self.test_pushButton_run = QPushButton(self.test)
        self.test_pushButton_run.setObjectName(u"test_pushButton_run")
        self.test_pushButton_run.setGeometry(QRect(630, 290, 101, 24))
        self.test_pushButton_save_arg = QPushButton(self.test)
        self.test_pushButton_save_arg.setObjectName(u"test_pushButton_save_arg")
        self.test_pushButton_save_arg.setGeometry(QRect(520, 290, 101, 24))
        self.test_comboBox_model = QComboBox(self.test)
        self.test_comboBox_model.addItem("")
        self.test_comboBox_model.addItem("")
        self.test_comboBox_model.addItem("")
        self.test_comboBox_model.setObjectName(u"test_comboBox_model")
        self.test_comboBox_model.setGeometry(QRect(210, 140, 111, 22))
        self.tabWidget.addTab(self.test, "")
        self.textBrowser_log = QTextBrowser(self.centralwidget)
        self.textBrowser_log.setObjectName(u"textBrowser_log")
        self.textBrowser_log.setGeometry(QRect(10, 420, 771, 251))
        self.textBrowser_log.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.pushButton_clear_log = QPushButton(self.centralwidget)
        self.pushButton_clear_log.setObjectName(u"pushButton_clear_log")
        self.pushButton_clear_log.setGeometry(QRect(640, 380, 101, 24))
        self.label_logging_browser = QLabel(self.centralwidget)
        self.label_logging_browser.setObjectName(u"label_logging_browser")
        self.label_logging_browser.setGeometry(QRect(20, 380, 151, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.preprocess_label_filename.setText(QCoreApplication.translate("MainWindow", u"Filename", None))
        self.preprocess_pushButton_save_arg.setText(QCoreApplication.translate("MainWindow", u"Save arguments", None))
        self.preprocess_pushButton_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.preprocess_label_outlier_detector.setText(QCoreApplication.translate("MainWindow", u"outlier_detector", None))
        self.preprocess_label_outlier_detector_param.setText(QCoreApplication.translate("MainWindow", u"outlier_detector_param", None))
        self.preprocess_label_train_size.setText(QCoreApplication.translate("MainWindow", u"train_size", None))
        self.preprocess_label_num_splits.setText(QCoreApplication.translate("MainWindow", u"num_splits", None))
        self.preprocess_comboBox_outlier_detector.setItemText(0, QCoreApplication.translate("MainWindow", u"Mean", None))
        self.preprocess_comboBox_outlier_detector.setItemText(1, QCoreApplication.translate("MainWindow", u"Median", None))
        self.preprocess_comboBox_outlier_detector.setItemText(2, QCoreApplication.translate("MainWindow", u"IF", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocess), QCoreApplication.translate("MainWindow", u"Preprocess", None))
        self.train_label_quiet.setText(QCoreApplication.translate("MainWindow", u"quiet", None))
        self.train_label_cuda.setText(QCoreApplication.translate("MainWindow", u"cuda", None))
        self.train_label_dataset.setText(QCoreApplication.translate("MainWindow", u"dataset", None))
        self.train_label_split_id.setText(QCoreApplication.translate("MainWindow", u"split_id", None))
        self.train_label_train_size.setText(QCoreApplication.translate("MainWindow", u"train_size", None))
        self.train_label_batch_size.setText(QCoreApplication.translate("MainWindow", u"batch_size", None))
        self.train_label_model.setText(QCoreApplication.translate("MainWindow", u"model", None))
        self.train_label_num_hidden_layers.setText(QCoreApplication.translate("MainWindow", u"num_hidden_layers", None))
        self.train_label_hidden_size.setText(QCoreApplication.translate("MainWindow", u"hidden_size", None))
        self.train_label_dropout.setText(QCoreApplication.translate("MainWindow", u"dropout", None))
        self.train_label_learning_rate.setText(QCoreApplication.translate("MainWindow", u"learning_rate", None))
        self.train_label_weight_decay.setText(QCoreApplication.translate("MainWindow", u"weight_decay", None))
        self.train_label_num_epochs.setText(QCoreApplication.translate("MainWindow", u"num_epochs", None))
        self.train_checkbox_quiet.setText("")
        self.train_comboBox_model.setItemText(0, QCoreApplication.translate("MainWindow", u"MLP", None))
        self.train_comboBox_model.setItemText(1, QCoreApplication.translate("MainWindow", u"ResNet", None))
        self.train_comboBox_model.setItemText(2, QCoreApplication.translate("MainWindow", u"Transformer", None))

        self.train_pushButton_save_arg.setText(QCoreApplication.translate("MainWindow", u"Save arguments", None))
        self.train_pushButton_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.train_label_quiet_description.setText(QCoreApplication.translate("MainWindow", u"Check if True", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.train), QCoreApplication.translate("MainWindow", u"Train", None))
        self.test_label_cuda.setText(QCoreApplication.translate("MainWindow", u"cuda", None))
        self.test_label_dataset.setText(QCoreApplication.translate("MainWindow", u"dataset", None))
        self.test_label_split_id.setText(QCoreApplication.translate("MainWindow", u"split_id", None))
        self.test_label_model.setText(QCoreApplication.translate("MainWindow", u"model", None))
        self.test_pushButton_run.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.test_pushButton_save_arg.setText(QCoreApplication.translate("MainWindow", u"Save arguments", None))
        self.test_comboBox_model.setItemText(0, QCoreApplication.translate("MainWindow", u"MLP", None))
        self.test_comboBox_model.setItemText(1, QCoreApplication.translate("MainWindow", u"ResNet", None))
        self.test_comboBox_model.setItemText(2, QCoreApplication.translate("MainWindow", u"Transformer", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.test), QCoreApplication.translate("MainWindow", u"Test", None))
        self.pushButton_clear_log.setText(QCoreApplication.translate("MainWindow", u"Clear log", None))
        self.label_logging_browser.setText(QCoreApplication.translate("MainWindow", u"Logging Browser", None))
    # retranslateUi

